#!/usr/bin/env python

import json
import logging
import time

import click
import google.protobuf.json_format as pb_json
import google.protobuf.message as msg

from erskafka.ERSSubscriber import ERSSubscriber

CONTEXT_SETTINGS = {"help_option_names": ["-h", "--help"]}

log = logging.getLogger("ers_subscriber_test")
log.addHandler(logging.StreamHandler())
log.setLevel(logging.DEBUG)


@click.command(context_settings=CONTEXT_SETTINGS)
@click.option(
    "--kafka-address",
    type=click.STRING,
    default="monkafka.cern.ch",
    help="address of the kafka broker",
)
@click.option(
    "--kafka-port", type=click.INT, default=30092, help="port of the kafka broker"
)
@click.option(
    "--running-seconds", type=click.INT, default=15, help="Number of seconds of the run"
)
def cli(kafka_address: str, kafka_port: int, running_seconds: int) -> None:
    """Subscribes to the ERS topic for the chosen amount of time."""
    bootstrap = f"{kafka_address}:{kafka_port}"

    conf = json.loads("{}")
    conf["bootstrap"] = bootstrap
    conf["timeout"] = 400

    sub = ERSSubscriber(conf)

    sub.add_callback(name="test", function=my_test_function)
    sub.add_callback(name="throwing", function=throwing_function)
    sub.add_callback(name="acceptable", function=acceptable_function, selection=".*")
    sub.add_callback(name="doomed", function=rejected_function, selection="[0-9]+")

    sub.start()
    time.sleep(running_seconds)
    sub.stop()


def my_test_function(issue: msg) -> None:
    """Convert message to JSON."""
    log.info(pb_json.MessageToJson(issue))


def acceptable_function(issue: msg) -> None:
    """An acceptable function."""
    log.info("Accepted")


def rejected_function(issue: msg) -> None:
    """A rejected function."""
    log.info("Rejected")


def throwing_function(issue: msg) -> None:
    """Function that throws."""
    log.info(issue.non_existent_entry)


if __name__ == "__main__":
    cli(show_default=True, standalone_mode=True)
