#!/usr/bin/env python3
import erskafka.ERSPublisher as erspub
from erskafka.ERSPublisher import ERSException  # import the custom exception
from time import sleep
import click

CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])

@click.command(context_settings=CONTEXT_SETTINGS)
@click.option('--kafka-address', type=click.STRING, default="monkafka.cern.ch", help="Address of the Kafka broker.")
@click.option('--kafka-port', type=click.INT, default=30092, help='Port of the Kafka broker.')
@click.option('--number-of-issues', type=click.INT, default=20, help='Number of issues to send.')

def cli(kafka_address, kafka_port, number_of_issues):
    bootstrap = f"{kafka_address}:{kafka_port}"
    conf = {"bootstrap": bootstrap}
    publisher = erspub.ERSPublisher(conf)

    for i in range(number_of_issues):
        message = f"This is issue with ID: {i}"
        result = publisher.publish_simple_message(message)
        print(f"Publishing issue {i}: {'successful' if result else 'failed'}")
        sleep(0.5)

    # Exception Test
    try:
        raise ERSException("This is a custom ERS exception for testing!")
    except ERSException as e:
        print(f"Caught an ERSException: {e}")
        result = publisher.publish_simple_message(str(e))
        print(f"Publishing exception message: {'successful' if result else 'failed'}")

if __name__ == '__main__':
    cli()

