#!/usr/bin/env python3
import click

import erskafka.ERSPublisher as erspub
from time import sleep

CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])

@click.command(context_settings=CONTEXT_SETTINGS)
@click.option('--kafka-address', type=click.STRING, default="monkafka.cern.ch", help="Address of the Kafka broker.")
@click.option('--kafka-port', type=click.INT, default=30092, help='Port of the Kafka broker.')
@click.option('--number-of-issues', type=click.INT, default=20, help='Number of issues to send.')

def cli(kafka_address, kafka_port, number_of_issues):
    bootstrap = f"{kafka_address}:{kafka_port}"
    conf = {"bootstrap": bootstrap}
    publisher = erspub.ERSPublisher(conf)

    for i in range(number_of_issues):
        message = f"This is issue with ID: {i}"
        result = publisher.publish_simple_message(message)
        print(f"Publishing issue {i}: {'successful' if result else 'failed'}")
        sleep(0.5)

if __name__ == '__main__':
    cli()

